[package]
authors = ["rotemy"]
description = "Alerting and monitoring framework"
edition = "2018"
license = "Apache-2.0"
name = "klaxon"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
